[build]
  command = "npm run build"
  publish = ".svelte-kit/build/"

[functions]
  directory = "functions/"
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda","apps-juaragcp-fullapps"]

[dev]
  targetPort = 5173
